# Generated by Django 3.1.4 on 2021-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('gt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('pro_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('seller', models.CharField(max_length=20)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('card_no', models.CharField(max_length=50, null=True)),
                ('card_name', models.CharField(max_length=50, null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
        ),
    ]
